name: funder-aws
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - boto3
  - pandas
  - selenium
  - pip
  - pip:
      - webdriver-manager
      - requests
      - aws-cdk-lib
      - constructs
